spring:
  session:
    store-type: redis
  redis:
    host: redis
    port: 6379
  security:
      oauth2:
        client:
          registration:
            keycloak:
              client-id: food
              client-secret: nUNjOiac04AYKI9VUagRakCMpHKsbzHk
              client-name: Keycloak
              scope: openid,profile,email
          provider:
            keycloak:
              issuer-uri: ${KEYCLOAK_URL:http://keycloak:8080}/auth/realms/food
  cloud:
    gateway:
      default-filters:
        - TokenRelay
        - RemoveRequestHeader=Cookie
      routes:
        - id: food-service
          uri: lb://food-service
          predicates:
            - Path=/api/foods/**
          filters:
            - name: Retry
              args:
                retries: 3
                methods: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
            - name: CircuitBreaker
              args:
                name: foodService
                fallbackUri: forward:/foods-fallback
        - id: meal-service
          uri: lb://meal-service
          predicates:
            - Path=/api/meals/**
          filters:
            - name: Retry
              args:
                retries: 3
                methods: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
            - name: CircuitBreaker
              args:
                name: mealService
                fallbackUri: forward:/meals-fallback        

resilience4j:
  circuitbreaker:
    instances:
      foodService:
        slidingWindowSize: 10
        permitterNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        registerHealthIndicator: true
  timelimiter:
    instances:
      foodService:
        timeoutDuration: 2s
